<?php

namespace AppBundle\Repository;

/**
 * EnderecoReposity
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnderecoRepository extends \Doctrine\ORM\EntityRepository
{
	public function getLatitudeLongitude()
	{
		return $this->getEntityManager()
					->createQuery("SELECT e.latitude, e.longitude FROM AppBundle:Endereco e")
					->getResult();
	}
}
